define({
    root: ({
        search: "Search: ",
        searchPlaceholder: "Find address or place",
        searchEnterCriteria: "Enter search term for",
        pressAlt: "Press ALT + digit keys for fast navigation",
        instructions: "instructions",
        moreHelp: "More Help",
        wcagViewer: "Accessible Viewer",
        leftCollapse: "Collapse Left Panel",
        leftExpand: "Expand Left Panel",
        moreHelp: "More Help",
        totalCount: "Total Count: {0}",
        contactUs: "Contact Us",
        EsriWorldGeocoder: "Esri World Geocoder",
        language: {
            aria: {
                changeLanguage: "Change the language to ",
                currentLanguage: "Current language is ",
            },
            language: "Language: ",
            changeHere: "Change the language here.",
            flag: "_ Flag"
        },
        tooltips: {
            "home": "Default Extent",
            "locate": "Find my Location",
            "features": "Feature List",
            "filter": "Filters",
            "infoPanel": "Info Panel",
            "geoCoding": "Reverse Geocode",
            "instructions": "Instructions",
            "legend": "Legend",
            "bookmarks": "Bookmarks",
            "layerManager": "Layer Manager",
            "layers": "Layers",
            "basemap": "Basemap Gallery",
            "overview": "Overview map",
            "measure": "Measure",
            "edit": "Edit",
            "time": "Time",
            "print": "Print",
            "details": "Details",
            "directions": "Directions",
            "share": "Share",
            "vsplitter": "Click and drag or focus and use left/right arrows to resize. \nDouble-click or type Enter for optimal size."
        },
        badgesTips: {
            "reverseLocation": "Showing Location",
            "directions": "Showing Itinerary",
            "featureSelected": "Feature Selected",
            "someFilters": "Some Filters Apply",
            "searchResultInfo": "Shows Search Result Info",
            "followTheMap": "Follow The Map Mode",
        },
        overview: {
            mapExtent: "Map Extent",
            instructions: "Drag to change the Map Extent,\nor focus and use Arrow keys.",
        },
        TOC: {
            visibleAtScale: "Visible at Scale",
            notVisibleAtScale: "Not Visible at Scale",
            openFeatureTable: "Open Feature Table",
            closeFeatureTable: "Close Feature Table",
        },
        FilterTab: {
            attribute: "Attribute:",
            add: "Add",
            remove: "Remove",
            apply: "Apply",
            ignore: "Ignore",
        },
        FilterItem: {
            remove: "Remove",
            equal: "Equal",
            notEqual: "Not Equal",
            like: "Like",
            notLike: "Not Like",
            in: "In",
            notIn: "Not In",
            lessThen: "Less Then",
            moreThen: "More Then",
            between: "Between",
            notBetween: "Not Between",
            selectCriteria: "Select criteria",
            enterValueToMatch: "Enter value to match",
            enterLastValue: "Enter last value",
            invalidNumber: "Invalid number format",
            enterDateToMatch: "Enter date to match",
            enterLastDate: "Enter last date",
            invalidDate: "Invalid date format",
        }
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "el": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sv": 1,
    "tr": 1,
    "th": 1,
    "vi": 1,
    "zh-cn": 1
});