define(
    ({
        search: "Recherche : ",
        searchPlaceholder: "Trouver une adresse ou un lieu",
        searchEnterCriteria: "Terme recherché pour",
        pressAlt: "Appuyer sur ALT + chiffre pour naviguer rapidement",
        instructions: "instructions.french",
        moreHelp: "Plus d'aide",
        wcagViewer: "Visualiseur Accessible",
        leftCollapse: "Réduire le panneau gauche",
        leftExpand: "Révéler le panneau gauche",
        moreHelp: "Plus d'aide",
        totalCount: "Le compte total : {0}",
        contactUs: "Contactez nous",
        EsriWorldGeocoder: "Géocodeur Mondial Esri",
        language: {
            aria: {
                changeLanguage: "Changer la langue en ",
                currentLanguage: "La langue actuelle est"
            },
            language: "Langue : ",
            changeHere: "Changer la langue ici.",
            flag: "Drapeau _"
        },
        tooltips: {
            "home": "Etendue par Défaut",
            "locate": "Rechercher mon Site",
            "legend": "Légende",
            "bookmarks": "Géosignets",
            "layerManager": "Gestionnaire de Couche",
            "layers": "Couches",
            "infoPanel": "Panneau d'information",
            "geoCoding": "Géocodage inversé",
            "instructions": "Mode d'emploi",
            "basemap": "Galerie des fonds de carte",
            "overview": "Vue Générale",
            "measure": "Mesurer",
            "edit": "Modifier",
            "time": "Heure",
            "print": "Imprimer",
            "details": "Détails",
            "directions": "Itinéraires",
            "share": "Partager",
            "filter": "Filtres",
            "features": "Liste de caractéristiques",
            "vsplitter": "Cliquer et déplacer avec la souris ou utiliser le flèches gauche droite quand cet outil est activé. \nDouble-cliquer ou presser ‘Entrer’ pour ajuster à la taille optimale."
        },
        badgesTips: {
            "reverseLocation": "Afficher l'adresse du lieu",
            "directions": "Montrer l'itinéraire",
            "featureSelected": "Caractéristique sélectionnée",
            "someFilters": "Appliqué quelques filtres",
            "searchResultInfo": "Montre Recherche Résultat",
            "followTheMap": "Mode Suivez la carte",
        },
        overview: {
            mapExtent: "Étendue de la carte",
            instructions: "Faites glisser pour modifier l'étendue de la carte, \nou mise au point et utiliser les touches fléchées.",
        },
        TOC: {
            visibleAtScale: "Visible à l'échelle",
            notVisibleAtScale: "Non visible à l'échelle",
            openFeatureTable: "Ouvrir la table des fonctionnalités",
            closeFeatureTable: "Fermer la table des fonctionnalités",
        },
        FilterTab: {
            attribute: "Attribut :",
            add: "Ajouter",
            apply: "Accepter",
            ignore: "Négliger",
        },
        FilterItem: {
            remove: "Supprimer",
            equal: "Égal",
            notEqual: "Different",
            like: "Comme",
            notLike: "Pas comme",
            in: "Dans",
            notIn: "Pas en",
            lessThen: "Moins que",
            moreThen: "Plus que",
            between: "Entre",
            notBetween: "Pas Entre",
            selectCriteria: "Choisir un critère",
            enterValueToMatch: "Entrer la valeur correspondante",
            enterLastValue: "Entrer la dernière valeur",
            invalidNumber: "Format de numéro non valide",
            enterDateToMatch: "Entrez la date pour correspondre",
            enterLastDate: "Entrez la dernière date",
            invalidDate: "La valeur entrée n'est pas une date valide.",
            missingDate: "Cette valeur est attendue.",
            rangeErrorDate: "La valeur est hors limites."

        }
    })
);