define({
    root: ({
        addressManager: {
            brokenRules: "Broken Rules",
            verifyRecord: "Verify Address Point Record",
            requiredNotProvided: "'{0}' is required but not provided.",
            incorrectFormat: "'{0}' has incorrect format.",
            tryFormat: "(Try '{0}')",
        }
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "el": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sv": 1,
    "tr": 1,
    "th": 1,
    "vi": 1,
    "zh-cn": 1
});